services:
  - type: web
    name: stock-analysis-web
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "480"
      - key: USERS
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: FOLDER_PENJUALAN
        sync: false
      - key: FOLDER_PRODUK
        sync: false
      - key: FOLDER_STOCK
        sync: false
      - key: FOLDER_HASIL_ANALISIS
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: CORS_ORIGINS
        sync: false
